name: Manual Docker Build and Push

on:
  workflow_dispatch:
    inputs:
      major_version:
        description: 'Major version number'
        required: true
        default: '1'
      reset_minor:
        description: 'Reset minor version counter'
        required: false
        default: 'false'
        type: boolean
      docker_hub_repo:
        description: 'Docker Hub repository (username/repo)'
        required: true
        default: 'your-dockerhub-username/9isuper-tools'

env:
  MINOR_VERSION_COUNTER: ${{ github.event.inputs.reset_minor == 'true' && '0' || (github.event.inputs.reset_minor == 'false' && (steps.minor_version.outputs.value || '0')) }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 获取或初始化副版本号
      - name: Get or initialize minor version
        id: minor_version
        run: |
          if [ "${{ github.event.inputs.reset_minor }}" = "true" ]; then
            echo "value=0" >> $GITHUB_OUTPUT
          else
            # 尝试从GitHub API获取当前副版本号
            MINOR=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/actions/variables" \
              | jq -r '.variables[] | select(.name == "MINOR_VERSION") | .value' || echo "0")
            # 副版本号+1
            MINOR=$((MINOR + 1))
            echo "value=$MINOR" >> $GITHUB_OUTPUT
          fi

      # 更新GitHub环境变量
      - name: Update minor version variable
        run: |
          curl -s -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/variables" \
            -d '{"name":"MINOR_VERSION","value":"${{ steps.minor_version.outputs.value }}"}' \
            || echo "Failed to update variable, continuing..."

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build:h5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ github.event.inputs.docker_hub_repo }}:latest
            ${{ github.event.inputs.docker_hub_repo }}:${{ github.event.inputs.major_version }}.${{ steps.minor_version.outputs.value }}
          build-args: |
            NODE_ENV=production