name: Manual Docker Build and Push

on:
  workflow_dispatch:
    inputs:
      major_version:
        description: 'Major version number'
        required: true
        default: '1'
      reset_minor:
        description: 'Reset minor version counter'
        required: false
        default: 'false'
        type: boolean
      docker_hub_repo:
        description: 'Docker Hub repository (username/repo)'
        required: true
        default: 'your-dockerhub-username/9isuper-tools'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 初始化版本号
      - name: Initialize version
        id: version
        run: |
          # 获取当前副版本号
          CURRENT_MINOR=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/variables" \
            | jq -r '.variables[] | select(.name == "MINOR_VERSION") | .value' || echo "0")
          
          # 处理重置逻辑
          if [ "${{ github.event.inputs.reset_minor }}" = "true" ]; then
            NEW_MINOR=0
          else
            NEW_MINOR=$((CURRENT_MINOR + 1))
          fi
          
          # 设置输出
          echo "major=${{ github.event.inputs.major_version }}" >> $GITHUB_OUTPUT
          echo "minor=$NEW_MINOR" >> $GITHUB_OUTPUT
          echo "full_version=${{ github.event.inputs.major_version }}.$NEW_MINOR" >> $GITHUB_OUTPUT

          # 更新变量
          curl -s -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/variables" \
            -d '{"name":"MINOR_VERSION","value":"'$NEW_MINOR'"}' \
            || echo "Failed to update variable, continuing..."

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build:h5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ github.event.inputs.docker_hub_repo }}:latest
            ${{ github.event.inputs.docker_hub_repo }}:${{ steps.version.outputs.full_version }}
          build-args: |
            NODE_ENV=production